### ISSUE TITLE
Selecting Photos Leads to Crash

### ISSUE THREAD

**Issue by locuturus** [w2sv/AutoCrop#35]
When using the new photo picker the app crashes. LogFox captured this:
> FATAL EXCEPTION: main
Process: com.w2sv.autocrop, PID: 19938
java.lang.NumberFormatException: Cannot parse null string
	at java.lang.Long.parseLong(Long.java:714)
	at java.lang.Long.parseLong(Long.java:876)
	at a2.i.j(Unknown Source:92)
	at com.w2sv.autocrop.activities.crop.a.j(Unknown Source:104)
	at a6.a.h(Unknown Source:8)
	at n6.c0.run(Unknown Source:110)
	at kotlinx.coroutines.internal.d.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(Unknown Source:76)
	Suppressed: androidx.datastore.preferences.protobuf.n1: [j1{Cancelling}@d5011c7, Dispatchers.Main.immediate]

**Comment by locuturus** [comment]
BTW, selecting the 3-dot menu in the photo picker screen and choosing browse opens DocumentsUI where you can successfully pick a photo.

**Comment by w2sv** [comment]
I just released [4.0.8](https://github.com/w2sv/AutoCrop/releases/tag/4.0.8), which hopefully resolves the issue. Let me know should it persist.

**Comment by w2sv** [comment]
Thanks for the supplementary log and sorry for the late reaction, btw.
