### ISSUE TITLE
Crash when returning from file/image selection

### ISSUE THREAD

**Issue by Sooperfish** [w2sv/AutoCrop#43]
Possibly related to #35

```
FATAL EXCEPTION: main
Process: com.w2sv.autocrop, PID: 4958
java.lang.ClassCastException: y2.h cannot be cast to android.app.Activity
	at m1.e.v(Unknown Source:43)
	at com.w2sv.autocrop.activities.examination.ExaminationActivity.J(Unknown Source:151)
	at C1.a.b(Unknown Source:39)
	at Y1.a.c(Unknown Source:303)
	at b.x.c(Unknown Source:41)
	at b.q.b(Unknown Source:23)
	at b.t.onBackInvoked(Unknown Source:2)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.lambda$onBackInvoked$5(WindowOnBackInvokedDispatcher.java:373)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.$r8$lambda$_fNMRb_sy9W4zyLHg8uTk4ezJHM(Unknown Source:0)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8291)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:557)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
```

**Comment by w2sv** [comment]
Doesn't look like it's related to #35. Could you describe the exact steps for reproducing the crash, as well as declare the used android version please?

**Comment by w2sv** [comment]
Also just out of interest: how did you obtain that log?

**Comment by Sooperfish** [comment]
> Also just out of interest: how did you obtain that log?

These are LogFox crash logs

> Doesn't look like it's related to #35. Could you describe the exact steps for reproducing the crash, as well as declare the used android version please?

My bad, I'm using Android 14 /Nothing OS 2.6 

I'm actually having trouble reproducing the bug. I've managed to inconsistently reproduce it twice by opening the image select, selecting an image and using the back gesture, and repeating this several times, but the LogFox log was inaccessible both times (LogFox freezes upon trying to open the log). 

I did however stumble into a crash when loading an image that _doesn't_ return the "No Crop Borders found" warning, using the back gesture, and using the back gesture again as suggested by the message bubble. Since it's caused by the back gesture it might be related? 

```
FATAL EXCEPTION: main
Process: com.w2sv.autocrop, PID: 8069
java.lang.ClassCastException: y2.h cannot be cast to android.app.Activity
	at m1.e.v(Unknown Source:43)
	at com.w2sv.autocrop.activities.examination.ExaminationActivity.J(Unknown Source:151)
	at C1.a.b(Unknown Source:39)
	at Y1.a.c(Unknown Source:303)
	at b.x.c(Unknown Source:41)
	at b.q.b(Unknown Source:23)
	at b.t.onBackInvoked(Unknown Source:2)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.lambda$onBackInvoked$5(WindowOnBackInvokedDispatcher.java:373)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.$r8$lambda$_fNMRb_sy9W4zyLHg8uTk4ezJHM(Unknown Source:0)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8291)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:557)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
```

Let me know if you need any other information.
